baseurl: "https://www.tilkov.com/"

title: "Stefan Tilkov"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
languageCode: en-us

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

params:
  description: "Stefan Tilkov"
  footer: "&copy; 2020-2023 [Stefan Tilkov](/about) | [Home](/) | [INNOQ](https://www.innoq.com/) | [RSS](/feed.atom) | <a rel=\"me\" href=\"https://innoq.social/@stilkov\">Mastodon</a>"
  mainSections: post

enableGitInfo: true


frontmatter:
  date:
    - :default

mediaTypes:
  application/atom+xml:
    suffixes:
    - atom

outputFormats:
  ATOM:
    name: ATOM
    baseName: feed
    mediaType: application/atom+xml


outputs:
  home:
  - HTML
  - ATOM
  - RSS
    
markup:
  goldmark:
    renderer:
      unsafe: true
